environment: &env
  CONTAINER: stable.world.auth
  DEPLOYMENT: auth
  GCLOUD_ZONE: us-central1-a
  GCLOUD_PROJECT: my-project-1-152801

version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install Dependencies
          command: .circleci/InstallBuildDependencies.sh
      - run:
          name: Install
          command: |
            pip install --upgrade pip setuptools wheel
            pip install -r ./requirements.txt
            python setup.py develop
      - run:
          name: Build apps
          command: |
            make buildApp
            make buildDockerPY2
            make buildDockerPY3
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: |
            make testPY2
            make testPY3
            ./bin/stable.world --help
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /workspace
          # Must be relative path from root
          paths:
            - bin/stable.world

  deploy-develop:
    working_directory: /workspace
    docker:
      - image: google/cloud-sdk
        # Environment variable for all commands executed in the primary container
        environment: *env
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /workspace
      - run:
          name: "Install Dependencies"
          command: .circleci/InstallDeployDependencies.sh
      - run:
          name: "Authorize Google Cloud"
          command: |
            make deploy-authorize
      - run:
          name: "Rollout to Stage"
          command: |
            make deploy

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy-develop:
          filters:
            branches:
              only: develop
          requires:
            - build
