environment: &env
  CONTAINER: stable.world.auth
  DEPLOYMENT: auth
  GCLOUD_ZONE: us-central1-a
  GCLOUD_PROJECT: my-project-1-152801

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.05.0-ce
      - run:
          name: Install Dependencies
          command: .circleci/InstallBuildDependencies.sh
      - run:
          name: Pip Install
          command: pip install --upgrade pip setuptools wheel
      - run:
          name: Build apps
          command: |
            make buildApp
            cp ./bin/stable.world $CIRCLE_ARTIFACTS
            make buildDockerPY2
            make buildDockerPY3
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: |
            make testPY2
            make testPY3
            ./bin/stable.world --help
#   post:
#
#     - python setup.py sdist bdist_wheel
#     - cp ./dist/* $CIRCLE_ARTIFACTS
#
# deployment:
#   development:
#     branch: develop
#     commands:
#       - pyenv global 2.7.12
#       - make deployFetch
#       - make deployAuthorize
#       - make deployDevelopment
#   master:
#     branch: master
#     commands:
#       - pyenv global 2.7.12
#       - make deployFetch
#       - make deployAuthorize
#       - make deployMaster
